### ISSUE TITLE
IOException: Sharing violation on path Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar

### ISSUE THREAD

**Issue by dzak83** [Microsoft/AppCenter-SDK-Unity#474] opened 2020-10-29 07:44 UTC
### **Description**

Error during a build after AppCenter upgrade:

**IOException: Sharing violation on path Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar**
System.IO.File.Delete (System.String path) (at <7ba07f088431485bb722f3b3373e87ee>:0)
AppCenterPreBuild.AddSettingsFileToLoader (AppCenterSettingsMakerAndroid settingsMaker) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:93)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.BuildTarget target, System.String path) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:37)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:21)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPreProcess>c__AnonStorey0.<>m__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:376)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

From what I understand, something is trying to access the same file twice.

### **Repro Steps**

1. Start building on Unity 2018.4.10 for Android. 
2. First time it will be successful
3. Build again and observe the error

In the git changes there are these files now:
![image](https://user-images.githubusercontent.com/27939815/97540059-4b9caf00-1980-11eb-947b-429b71d85d60.png)

### **Details**

1. Which SDK version are you using?
    - 3.3.1
2. Which platform did you experience the issue on?
    - Android latest
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Building for Google Pixel 2 but it doesn't matter
4. What third party plugins are you using?
5. Please enable verbose logging for your app using **Initial Log Level** setting and include the logs here:

    Directory: 

Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        10/29/2020  12:41 AM                appcenter-loader-release                                             

UnityEngine.Debug:Log(Object)
AndroidLibraryHelper:ExecuteProcess(String, String) (at Assets/AppCenter/Editor/AndroidLibraryHelper.cs:105)
AndroidLibraryHelper:UnzipFile(String, String) (at Assets/AppCenter/Editor/AndroidLibraryHelper.cs:81)
AppCenterPreBuild:AddSettingsFileToLoader(AppCenterSettingsMakerAndroid) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:78)
AppCenterPreBuild:OnPreprocessBuild(BuildTarget, String) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:37)
AppCenterPreBuild:OnPreprocessBuild(BuildReport) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:21)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

IOException: Sharing violation on path Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar
System.IO.File.Delete (System.String path) (at <7ba07f088431485bb722f3b3373e87ee>:0)
AppCenterPreBuild.AddSettingsFileToLoader (AppCenterSettingsMakerAndroid settingsMaker) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:93)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.BuildTarget target, System.String path) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:37)
AppCenterPreBuild.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Assets/AppCenter/Editor/AppCenterPreBuild.cs:21)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPreProcess>c__AnonStorey0.<>m__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:376)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error building Player: IOException: Sharing violation on path Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar

Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x00242] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:194 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x0007f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:97 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

6. Please share a screenshot of App Center Settings (without app secrets)
![image](https://user-images.githubusercontent.com/27939815/97539761-c6b19580-197f-11eb-8a4f-ee033e6539bf.png)

7. Please share a screenshot of Build and Player Settings.
![image](https://user-images.githubusercontent.com/27939815/97539800-d630de80-197f-11eb-871b-cc0d9a610a61.png)
![image](https://user-images.githubusercontent.com/27939815/97539871-f5c80700-197f-11eb-8bc3-95b07d2f2ce7.png)

**Comment by olmisa** [comment] 2020-10-29 17:46
Hello @dzak83 ,
thanks for getting us in touch. 
I was not able to reproduce this issue on my local environment. Is it possible that several processes trying to use same files at the same time in your environment?
Thanks

**Comment by dzak83** [comment] 2020-10-29 22:41
I am not sure what else could cause it in the project. I also have to say that today it was less consistent. 

In the AppCenterPreBuild I understand that you are unzipping it, putting some settings and zip again. Is there a workaround? Can I just zip it once, comment that code in the AddSettingsFileToLoader and check-in the aar ?

**Comment by olmisa** [comment] 2020-10-30 10:19
Hello @dzak83 ,
we are adding current app center settings to app loader. App loader use these settings. These settings could be change from Unity. That is why they should be added dynamically.
Is it possible to provide a sample project which could reproduce the error? 
Could you, please, try to reproduce this issue on empty project?
Thanks

**Comment by dzak83** [comment] 2020-11-03 07:48
Hi,
I think I solved it by removing read-only permissions from the file:

File.SetAttributes(loaderZipFile, FileAttributes.Normal);
File.Delete(loaderZipFile);

Something (git?) is setting read-only on all files in the solution. Making sure that attribute is removed, solved the problem.

**Comment by dzak83** [comment] 2020-11-03 08:33
I am 99% sure it's caused by VS 2019 open at the same time (project launched from Unity). It's annoying though since I need VS to code the project.

**Comment by DmitriyKirakosyan** [comment] 2020-11-03 11:49
Hi @dzak83,
Unfortunately, we could not reproduce the issue. We tried to build and debug the project running VS2019 and Unity at the same time and everything worked well.

Could you please provide more info about your environment for us to be able to investigate the issue further?
- Do you have vs-code or any other tool/editor opened with the same project in parallel?
- Could you also check what process(es) is locking the file `appcenter-loader-release.aar`? Here are the tips on how to figure it out: https://superuser.com/a/643312

**Comment by dzak83** [comment] 2020-11-04 06:06
I tried few more times today. I had this issue few times in a row with Unity and VS open. I closed VS, everything was fine few times and then I opened VS2019 and I got the repro.

Process Explorer and Resource Monitor didn't show anything so I assume the file is locked for just a moment, which would explain why repro is not consistent. 

I only have VS2019, no vs-code or any other editor

**Comment by DmitriyKirakosyan** [comment] 2020-11-04 19:22
@dzak83 , When did you start facing this issue?
If it started to happen on the AppCenter lib update, what was the version that you used before?

**Comment by DmitriyKirakosyan** [comment] 2020-11-05 07:33
~@dzak83 If I understand it correctly, you have this file in your git repository, which probably causes this IOException.~

~Could you try to add the file to gitignore file? Use `git rm --cached  Assets/AppCenter/Plugins/Android/appcenter-loader-release.aar` to remove the file from git index (see https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio#permanently-stop-tracking-a-file)
Note, that you don't need to track this file in your repository to be able to build the project.~

**Comment by dzak83** [comment] 2020-11-05 09:14
I tried git changes but that didn't help.

Previous version was something 2.* (definitely we were not on 3). I would need to go back in git history to confirm exactly what we used. Let me know you need it.

Today I am closing VS2019 every time I build and it's the only way it works.

**Comment by DmitriyKirakosyan** [comment] 2020-11-05 14:09
@dzak83 ,

Could you please share your `Scripting Backend` [configuration](https://docs.unity3d.com/2018.3/Documentation/Manual/windowsstore-scriptingbackends.html)? Could you try to switch it and check if it helps?

If you have a chance, please try to reproduce the issue on a test application or the [SDK Demo App](https://github.com/microsoft/appcenter-sdk-unity/tree/develop/AppCenterDemoApp).

Also, it would be really helpful if you could try these SDK versions: \<your-previous-version\>, 2.6.0, 3.1.0 and 3.1+ and check which version is the breaking one.

Thanks.

**Comment by dzak83** [comment] 2020-11-06 04:48
It's an Android, so I have Mono option to switch to from IL2CPP. I tried that and also App Compatibility Level. Same repro

![image](https://user-images.githubusercontent.com/27939815/98327382-350ddd80-1fa8-11eb-9d2e-ca4b6806a649.png)

**Comment by dzak83** [comment] 2020-11-06 05:20
I also tried the SDK demo app. I added AppCenter extension and installed 3.3.1 version. No repro with VS open. It has to be specific to our project then.

**Comment by DmitriyKirakosyan** [comment] 2020-11-06 07:38
@dzak83,

Thanks for spending time on investigating and reproducing!

The file `appcenter-loader-release.aar` is in gitignore in the sdk repo: https://github.com/microsoft/appcenter-sdk-unity/blob/develop/.gitignore#L50.
Could you try to remove this line from gitignore, build and commit the file. Then change the code, build again and check if it reproduces.

Also, do you have any specific git settings that could potentially cause that problem?

**Comment by vvechkanov** [comment] 2020-11-18 13:36
@dzak83,
 Hi, hope you are doing well! 
We haven’t heard from you in a while, do you still need assistance with this issue? Please let us know.

**Comment by vvechkanov** [comment] 2020-11-19 08:51
I am closing this for now. Feel free to comment/reopen if you need further assistance.

**Closed as completed by vvechkanov** 2020-11-19 08:51 UTC
Labels: support
