### ISSUE TITLE
Errors are not reported to AppCenter (Android)

### ISSUE THREAD

**Issue by liortal53** [Microsoft/AppCenter-SDK-Unity#219] opened 2018-12-11 21:26 UTC
I have added the Crashes unityPackage and set up the integration as required, but could not get any reports showing up on our app's dashboard.

Also, it is unclear whether the Analytics package is required as well if all i'm interested in is crashes / errors data.

**Comment by kostya-zhidovinov** [comment] 2018-12-12 12:42
Hi @liortal53 !
This seems to be a known bug in Unity for Android. Unity catches all exceptions and prevents application crashes, so application is still running. 
Please take a look at this note for more info:  https://docs.microsoft.com/en-us/appcenter/sdk/crashes/unity#generate-a-test-crash

As for your last question - no analytics is required, the App Center SDKs use a modular architecture so you can use any or all of the services.

Please let me know if you need any further assistance with this or if you have more questions.

**Comment by tallior** [comment] 2018-12-12 12:47
Commenting from my other (work) account - i saw the code, you are registering on the logMessageReceived delegate, so i should be seeing errors as well (not only crashes), but unfortunately i received nothing.

**Comment by kostya-zhidovinov** [comment] 2018-12-12 14:57
Hey @tallior, could you please switch to LogLevel `verbose` from AppCenterBehaviour settings, reproduce this case and send me logs to investigate? Also if you have a simple app where I can reproduce this on my side - that would help a lot.

**Comment by tallior** [comment] 2018-12-19 15:53
i actually found the issue - i had to modify our proguard file to not strip
appcenter related classes from the build (Android)

**Comment by evgeny-pol** [comment] 2018-12-20 08:04
Hello @tallior , good to hear you've managed to resolve the issue!
Do you mind sharing with us the piece of code that helped you to do it?
I'm going to close this issue for now but feel free to reopen it if you have any further questions.

**Closed as completed by evgeny-pol** 2018-12-20 08:04 UTC

**Comment by tallior** [comment] 2018-12-20 11:01
We are using proguard (to strip unused Java classes from the produced apk).
In our proguard-user.txt file I had to add this line (i already deleted the branch, so i am not sure this is exactly the package name for your code):

`-keep class com.microsoft.appcenter.** { *; }`

**Comment by jonesvgonc** [comment] 2022-02-16 22:32
I am facing a similar issue, but i am not using proguard, I think the problem is that I am using the AppCenter inside of a Package, created all of the things that I need with AppCenter inside of this package and calling it in my project..... I do not know if it is something that can cause this problem, but I have tested with a test project and the AppCenter send crash report, but inside of my project that use Packages it not works....
