### ISSUE TITLE
error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by vengefullfoot** [Microsoft/AppCenter-SDK-Unity#507] opened 2021-12-08 19:37 UTC
### **Description**

I'm getting error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?) in AppCenterBehaviour.cs

I've tried to solve it using asmdef, foring the resolution of the dll, but it just moves the issue to AppCenter/Plugins/AppCenterSDK/Analytics/Shared/Analytics.cs ...

Any idea ?
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Start a build
2. Build fails

### **Details**

1. Which SDK version are you using?
   4.3.0
2. Which platform did you experience the issue on?
    Unity 2021.2.4f1 (Android and iOS)
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    During build

**Comment by AnastasiaKubova** [comment] 2021-12-09 06:14
Hi! Thanks for getting in touch with us!
Could you please clarify what App Center SDK version you used before? Or do you use the App Center SDK the first time?
How do you integrate the App Center SDK - via extension or manually?

**Comment by vengefullfoot** [comment] 2021-12-09 08:54
Hello. I've just started to change my workflow to add appCenter, so I haven't used a previous SDK version than 4.3.0 with this project. I used the extension to download the 3 parts of the SDK.

**Comment by vengefullfoot** [comment] 2021-12-09 08:57
To clarify also, I only have the issue when building for release, not when I just build the player for testing locally (and I don't get any warning in VS about this Internal namespace missing)

**Comment by AnastasiaKubova** [comment] 2021-12-09 09:31
Thanks for the details. Does this issue happen for release build for both platforms (Android and iOS)? 
Have you a chance to check this behavior with the previous App Center SDK version ([4.2.0](https://github.com/microsoft/appcenter-sdk-unity/releases/tag/4.2.0)) and let me know about the results?

**Comment by vengefullfoot** [comment] 2021-12-09 10:28
Yes it happens on both platforms.
I've tried uninstalling and just reinstalling Analytics part, and I still get the same issue:

```
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/Analytics.cs(6,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/EventProperties.cs(6,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/PropertyConfigurator.cs(4,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/TransmissionTarget.cs(4,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
*** Tundra build failed (0.34 seconds), 115 items updated, 693 evaluated
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/Analytics.cs(6,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/EventProperties.cs(6,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/PropertyConfigurator.cs(4,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
Assets/AppCenter/Plugins/AppCenterSDK/Analytics/Shared/TransmissionTarget.cs(4,43): error CS0234: The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AppCenter.Unity.Analytics' (are you missing an assembly reference?)
[ScriptCompilation] Requested script compilation because: Recompiling scripts for editor because player build failed.
Error building Player because scripts had compiler errors
```

**Comment by AnastasiaKubova** [comment] 2021-12-09 10:41
Thanks for checking it. I tried to reproduce this issue on an empty test app and for me all work well. Looks like the Analytics module is not installed in your project. Could you please try to install the Analytics module [manually](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity#31b-install-individual-packages) (just download and install the Analytics module from GitHub)?

**Comment by vengefullfoot** [comment] 2021-12-12 20:40
The thing is the Analytics was installed. I don't understand why it is not found at compile time. I also tried  to reproduce on an empty project and it works.

**Comment by AnastasiaKubova** [comment] 2021-12-13 07:50
Thanks for the details! I also double checked this behavior and for me, all work well. I can suggest you try to remove the App Center extension, clean the cache and reinstall all App Center modules manually. Unfortunately without additional information or reproducing steps it will be problematic to figure out what exactly goes wrong.

**Comment by AnastasiaKubova** [comment] 2021-12-16 10:03
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Closed as completed by AnastasiaKubova** 2021-12-16 10:03 UTC
Labels: support
