### ISSUE TITLE
App Center Behavior should have only one instance!

### ISSUE THREAD

**Issue by hippogamesunity** [Microsoft/AppCenter-SDK-Unity#528] opened 2022-10-26 18:42 UTC
### **Description**

When you reload a scene with AppCenterBehaviour (which is a common use case), the plugin logs the error: "App Center Behavior should have only one instance". I think you should remove this error message.

### **Repro Steps**

1. Add AppCenterBehaviour to a scene
2. Play, then reload the scene, get the error

### **Details**

1. Which SDK version are you using?
    - 4.4.0
2. Which platform did you experience the issue on?
    - Any

**Comment by AnatolyPristensky** [comment] 2022-10-27 15:41
Hello @hippogamesunity, it's by design. 
Could you please clarify, why it's not possible to setup it in main scene which is not refreshing?

**Comment by hippogamesunity** [comment] 2022-10-27 18:08
Hi! I think it's a common approach when you have a main scene (like menu) and other scenes (like battle). When a battle is over, you need to return to the main scene (and don't want to get any errors).

**Comment by AnatolyPristensky** [comment] 2022-10-28 09:19
@hippogamesunity, according to [Unity documentation ](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Awake.html) awake is calling once in scene lifecycle. If the scene was unloaded - it's calling again. 
Could you please confirm that you doing unload the scene and then reload it? If so - this behaviour is expected and you can ignore this message.

**Comment by hippogamesunity** [comment] 2022-10-28 09:22
Yes, Awake is called twice if a scene is loaded twice, that's why your plugin logs error while it's not actually an error but a legal/normal use case.

**Comment by hippogamesunity** [comment] 2022-10-28 09:24
I suggest just removing the error message.
Also do you know about DontDestroyOnLoad? Most likely it's what you need. Many other plugins use this feature to leave their behaviour object across different scenes.

https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

**Comment by AnatolyPristensky** [comment] 2022-10-28 09:59
@hippogamesunity, actually we are already using DontDestroyOnLoad - https://github.com/microsoft/appcenter-sdk-unity/blob/c563a393e028ec5f6d93695f4a2489170a02e3e1/Assets/AppCenter/AppCenterBehavior.cs#L33

But anyway, thank you for your suggestion, I've marked it as a feature request.

**Comment by DmitriyKirakosyan** [comment] 2024-04-15 04:35
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed as not planned by DmitriyKirakosyan** 2024-04-15 04:35 UTC
Labels: support, feature request
