### ISSUE TITLE
Unity / Can't build UWP project with AppCenter Analytics in Visual Studio

### ISSUE THREAD

**Issue by hippogamesunity** [Microsoft/AppCenter-SDK-Unity#526] opened 2022-10-25 12:10 UTC
### **Description**

Can't build UWP project with AppCenter Analytics in Visual Studio

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new project in Unity 2021 or 2022, import AppCenter Analytics package
2. Build D3D project with Unity, open it in Visual Studio
3. Try to build, there are a lot of errors occure
4. I can build with no issues if I delete the asset. The asset works fine on Android BTW.

### **Details**

1. Which SDK version are you using?
    - 4.4.0
2. Which platform did you experience the issue on?
    - UWP
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Windows 11
![image](https://user-images.githubusercontent.com/7318172/197769525-bdf1ab01-cf66-4c30-b26c-7c4d832f6d15.png)
![image](https://user-images.githubusercontent.com/7318172/197769376-0d110543-cd19-455a-9841-08f11394d82a.png)
![image](https://user-images.githubusercontent.com/7318172/197769451-f187a278-279b-4487-aeac-f6ddd71c38f1.png)

**Comment by hippogamesunity** [comment] 2022-10-25 12:13
Can be the same issue as https://github.com/microsoft/appcenter-sdk-unity/issues/513

**Comment by AnatolyPristensky** [comment] 2022-10-25 13:41
Hello @hippogamesunity, 
Yes, this is the same issue. Closing it as duplicate of https://github.com/microsoft/appcenter-sdk-unity/issues/513

**Closed as completed by AnatolyPristensky** 2022-10-25 13:41 UTC
Labels: support
